const tempTasks = [
  {
    id: 1,
    tId: "ec-101",
    title: "create navbar ui",
    desc: "create navbar ui",
    type: "new-feature",
    status: "inProgress",
    createdDate: "2023-08-15T11:00:00+00:00",
    priority: 6,
  },
  {
    id: 2,
    tId: "ecc-351",
    title: "create tasks data model",
    desc: "create tasks data model save it in js, and export it",
    type: "issue",
    status: "completed",
    createdDate: "2023-08-15T11:02:00+00:00",
    priority: 3,
  },
  {
    id: 3,
    tId: "ft-101",
    title: "save sample tasks data model to redux",
    desc: "save sample tasks data model to redux",
    type: "issue",
    status: "toDo",
    createdDate: "2023-08-15T11:04:00+00:00",
    priority: 2,
  },
  {
    id: 4,
    tId: "bg-10",
    title: "get the unique status fields which you find inside task list",
    desc: "get the unique status fields which you find inside task list",
    type: "new-feature",
    status: "toDo",
    createdDate: "2023-08-15T11:05:00+00:00",
    priority: 4,
  },
  {
    id: 5,
    tId: "ft-102",
    title:
      "Render columns based on unique status fields which you find inside task list",
    desc: "Render columns based on unique status fields which you find inside task list",
    type: "new-feature",
    status: "toDo",
    createdDate: "2023-08-15T11:05:00+00:00",
    priority: 6,
  },
  {
    id: 6,
    tId: "ft-102",
    title: "List tasks under each of the column",
    desc: "List tasks under each of the column",
    type: "issue",
    status: "toDo",
    createdDate: "2023-08-15T11:06:00+00:00",
    priority: 6,
  },
  {
    id: 7,
    tId: "ft-102",
    title: "implement Create task page ui",
    desc: "implement Create task page ui",
    type: "new-feature",
    status: "toDo",
    createdDate: "2023-08-15T11:08:00+00:00",
    priority: 6,
  },
  {
    id: 8,
    tId: "ft-102",
    title: "implement Create task page logic",
    desc: "implement Create task page logic",
    type: "new-feature",
    status: "toDo",
    createdDate: "2023-08-15T11:10:00+00:00",
    priority: 6,
  },
];

export default tempTasks;
